version: '3'
services:
    devcontainer:
        build: .
        command: sleep infinity
        environment: 
            - "REDIS_HOST=redis"
        volumes:
            - ..:/workspace/LoadAvg
            - ~/.gitconfig:/root/.gitconfig
            - ~/.ssh:/root/.ssh
    redis:
        image: redis:5
        ports:
            - 6379:6379
